-- ===========================================================================
-- V001__baseline.sql
-- Generated 2026-05-04 from Hibernate-managed schema (Spring Boot 3.4.4 + JPA).
-- This is the canonical baseline. From this point on, all schema changes are
-- versioned Flyway migrations (V002, V003, ...). spring.jpa.hibernate.ddl-auto = validate
-- in every profile from now on.
-- ===========================================================================

--
--






--
-- Name: api_rate_limits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_rate_limits (
    id character varying(255) NOT NULL,
    state bytea
);


--
-- Name: audit_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_events (
    id bigint NOT NULL,
    actor_email character varying(150),
    actor_role character varying(30),
    actor_user_id bigint,
    created_at timestamp(6) without time zone,
    details text,
    entity_id bigint,
    entity_type character varying(80),
    event_type character varying(100) NOT NULL,
    ip_address character varying(45),
    new_value text,
    old_value text,
    request_id character varying(64),
    user_agent text
);


--
-- Name: audit_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: availability_slots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.availability_slots (
    id bigint NOT NULL,
    assigned_guide_email character varying(150),
    assigned_guide_name character varying(150),
    booked_count integer NOT NULL,
    created_at timestamp(6) without time zone,
    max_capacity integer NOT NULL,
    slot_date date NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    experience_id bigint NOT NULL,
    CONSTRAINT availability_slots_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'LIMITED'::character varying, 'FULLY_BOOKED'::character varying, 'REQUEST_ONLY'::character varying])::text[])))
);


--
-- Name: availability_slots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.availability_slots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.availability_slots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blackout_dates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blackout_dates (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    date_value date NOT NULL,
    reason character varying(300),
    experience_id bigint NOT NULL
);


--
-- Name: blackout_dates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.blackout_dates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blackout_dates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blog_post_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blog_post_tags (
    post_id bigint NOT NULL,
    tag character varying(50)
);


--
-- Name: blog_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blog_posts (
    id bigint NOT NULL,
    author_display_name character varying(150),
    category character varying(30) NOT NULL,
    content text NOT NULL,
    cover_media_id bigint,
    created_at timestamp(6) without time zone,
    excerpt character varying(500),
    featured_image_url character varying(255),
    is_highlighted boolean DEFAULT false,
    meta_description character varying(400),
    meta_title character varying(200),
    published boolean NOT NULL,
    published_at timestamp(6) without time zone,
    slug character varying(350) NOT NULL,
    title character varying(300) NOT NULL,
    updated_at timestamp(6) without time zone,
    view_count bigint,
    author_id bigint,
    CONSTRAINT blog_posts_category_check CHECK (((category)::text = ANY ((ARRAY['UPDATE'::character varying, 'EVENT'::character varying, 'STORY'::character varying, 'CULTURE'::character varying, 'CONSERVATION'::character varying, 'TESTIMONIAL'::character varying])::text[])))
);


--
-- Name: blog_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.blog_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id bigint NOT NULL,
    admin_notes text,
    alternative_date date,
    booking_reference character varying(30) NOT NULL,
    confirmed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    group_size integer NOT NULL,
    guest_country character varying(100),
    guest_email character varying(150) NOT NULL,
    guest_name character varying(150) NOT NULL,
    guest_phone character varying(30),
    payment_method character varying(50),
    payment_status character varying(20),
    preferred_date date NOT NULL,
    preferred_language character varying(30),
    special_requests text,
    status character varying(20) NOT NULL,
    total_price numeric(10,2),
    tour_operator_email character varying(150),
    tour_operator_name character varying(200),
    updated_at timestamp(6) without time zone,
    experience_id bigint,
    user_id bigint,
    CONSTRAINT bookings_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['UNPAID'::character varying, 'PARTIAL'::character varying, 'PAID'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT bookings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    added_at timestamp(6) without time zone,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts (
    id bigint NOT NULL,
    anon_session_id character varying(100),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint
);


--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consent_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consent_records (
    id bigint NOT NULL,
    consent_type character varying(80) NOT NULL,
    consented boolean NOT NULL,
    created_at timestamp(6) without time zone,
    source character varying(120),
    subject_email character varying(150) NOT NULL
);


--
-- Name: consent_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consent_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consent_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact_inquiries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_inquiries (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(150) NOT NULL,
    full_name character varying(150) NOT NULL,
    message text NOT NULL,
    phone character varying(40),
    status character varying(20) NOT NULL,
    subject character varying(80) NOT NULL,
    CONSTRAINT contact_inquiries_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'IN_PROGRESS'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: contact_inquiries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_inquiries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_inquiries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donation_campaigns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.donation_campaigns (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    donor_count integer,
    goal_amount numeric(12,2),
    image_url character varying(255),
    impact_statement character varying(500),
    impact_tiers text,
    name character varying(200) NOT NULL,
    raised_amount numeric(12,2),
    updated_at timestamp(6) without time zone
);


--
-- Name: donation_campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.donation_campaigns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donation_campaigns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.donations (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    currency character varying(3) NOT NULL,
    donor_country character varying(100),
    donor_email character varying(150) NOT NULL,
    donor_name character varying(200) NOT NULL,
    is_anonymous boolean,
    is_recurring boolean,
    message text,
    payment_method character varying(50),
    purpose character varying(30) NOT NULL,
    recurring_frequency character varying(20),
    status character varying(20) NOT NULL,
    transaction_id character varying(200),
    campaign_id bigint,
    user_id bigint,
    CONSTRAINT donations_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['GENERAL'::character varying, 'REFORESTATION'::character varying, 'COMMUNITY_EDUCATION'::character varying, 'YOUTH_EMPOWERMENT'::character varying, 'CONSERVATION'::character varying])::text[]))),
    CONSTRAINT donations_recurring_frequency_check CHECK (((recurring_frequency)::text = ANY ((ARRAY['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'ANNUALLY'::character varying])::text[]))),
    CONSTRAINT donations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: donations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.donations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experience_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experience_images (
    experience_id bigint NOT NULL,
    image_url character varying(255)
);


--
-- Name: experiences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experiences (
    id bigint NOT NULL,
    active boolean NOT NULL,
    available_daily boolean,
    available_days character varying(100),
    booking_type character varying(20) NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    duration_hours numeric(4,1),
    experience_type character varying(30) NOT NULL,
    featured boolean,
    group_price numeric(10,2),
    languages_offered character varying(100),
    location character varying(300),
    max_group_size integer,
    meeting_point character varying(300),
    min_group_size integer,
    price_note character varying(300),
    price_per_person numeric(10,2),
    primary_image_url character varying(255),
    primary_media_id bigint,
    short_description character varying(500),
    slug character varying(250) NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone,
    what_to_bring text,
    whats_included text,
    CONSTRAINT experiences_booking_type_check CHECK (((booking_type)::text = ANY ((ARRAY['DIRECT'::character varying, 'INQUIRY'::character varying])::text[]))),
    CONSTRAINT experiences_experience_type_check CHECK (((experience_type)::text = ANY ((ARRAY['CULTURAL'::character varying, 'VILLAGE'::character varying, 'CONSERVATION'::character varying, 'CUSTOM'::character varying])::text[])))
);


--
-- Name: experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media_assets (
    id bigint NOT NULL,
    alt_text character varying(250),
    content_type character varying(120),
    created_at timestamp(6) without time zone,
    file_size_bytes bigint,
    public_url character varying(700) NOT NULL,
    storage_key character varying(500) NOT NULL,
    title character varying(250)
);


--
-- Name: media_assets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.media_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_logs (
    id bigint NOT NULL,
    channel character varying(20) NOT NULL,
    created_at timestamp(6) without time zone,
    external_reference character varying(200),
    message_body text,
    recipient character varying(160) NOT NULL,
    status character varying(20) NOT NULL,
    subject character varying(220),
    CONSTRAINT notification_logs_channel_check CHECK (((channel)::text = ANY ((ARRAY['EMAIL'::character varying, 'WHATSAPP'::character varying])::text[]))),
    CONSTRAINT notification_logs_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: notification_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    price_at_purchase numeric(12,2) NOT NULL,
    product_image_url character varying(255),
    product_name character varying(200) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platform_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platform_settings (
    id bigint NOT NULL,
    category character varying(60) NOT NULL,
    description character varying(300),
    key_name character varying(120) NOT NULL,
    masked boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by character varying(150),
    value_data text
);


--
-- Name: platform_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.platform_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platform_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_categories (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    display_order integer,
    image_url character varying(255),
    name character varying(120) NOT NULL,
    slug character varying(150) NOT NULL
);


--
-- Name: product_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_collections (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    display_order integer,
    name character varying(120) NOT NULL,
    slug character varying(150) NOT NULL
);


--
-- Name: product_collections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    product_id bigint NOT NULL,
    image_url character varying(255)
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    artist_name character varying(150),
    artist_story text,
    artwork_status character varying(20) NOT NULL,
    available boolean NOT NULL,
    compare_at_price numeric(12,2),
    created_at timestamp(6) without time zone,
    description text,
    dimensions character varying(100),
    featured boolean,
    inventory_type character varying(20) NOT NULL,
    medium character varying(100),
    name character varying(200) NOT NULL,
    price numeric(12,2) NOT NULL,
    primary_image_url character varying(255),
    reserved_quantity integer,
    reserved_until timestamp(6) without time zone,
    shippable boolean,
    shipping_note character varying(500),
    short_description character varying(500),
    slug character varying(250) NOT NULL,
    stock_quantity integer,
    updated_at timestamp(6) without time zone,
    weight_kg numeric(6,2),
    category_id bigint,
    collection_id bigint,
    CONSTRAINT products_artwork_status_check CHECK (((artwork_status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'SOLD'::character varying, 'ARCHIVED'::character varying])::text[]))),
    CONSTRAINT products_inventory_type_check CHECK (((inventory_type)::text = ANY ((ARRAY['UNIQUE'::character varying, 'BATCH'::character varying])::text[])))
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    approved boolean NOT NULL,
    approved_at timestamp(6) without time zone,
    comment text NOT NULL,
    created_at timestamp(6) without time zone,
    featured boolean NOT NULL,
    rating integer NOT NULL,
    reviewer_country character varying(100),
    reviewer_email character varying(150),
    reviewer_name character varying(150) NOT NULL,
    experience_id bigint,
    product_id bigint,
    user_id bigint
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    description character varying(200),
    name character varying(30) NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saved_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: saved_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saved_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipping_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipping_orders (
    id bigint NOT NULL,
    address_line1 character varying(300) NOT NULL,
    address_line2 character varying(300),
    admin_notes text,
    carrier character varying(20) NOT NULL,
    city character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    created_at timestamp(6) without time zone,
    currency character varying(3) NOT NULL,
    delivered_at timestamp(6) without time zone,
    order_reference character varying(30) NOT NULL,
    payment_method character varying(50),
    payment_status character varying(20) NOT NULL,
    payment_transaction_id character varying(200),
    postal_code character varying(20),
    product_total numeric(12,2) NOT NULL,
    quantity integer NOT NULL,
    recipient_email character varying(150) NOT NULL,
    recipient_name character varying(200) NOT NULL,
    recipient_phone character varying(30),
    shipped_at timestamp(6) without time zone,
    shipping_cost numeric(10,2),
    state character varying(100),
    status character varying(20) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    tracking_number character varying(100),
    tracking_url character varying(500),
    updated_at timestamp(6) without time zone,
    product_id bigint,
    user_id bigint,
    CONSTRAINT shipping_orders_carrier_check CHECK (((carrier)::text = ANY ((ARRAY['FEDEX'::character varying, 'LOCAL'::character varying])::text[]))),
    CONSTRAINT shipping_orders_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['UNPAID'::character varying, 'PAID'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT shipping_orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'RETURNED'::character varying])::text[])))
);


--
-- Name: shipping_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipping_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipping_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: talent_applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.talent_applications (
    id bigint NOT NULL,
    accessibility_needs character varying(500),
    admin_notes text,
    age_range character varying(30),
    applicant_category character varying(30) NOT NULL,
    availability_details character varying(500),
    created_at timestamp(6) without time zone,
    email character varying(150),
    experience_description text,
    feedback_to_applicant text,
    full_name character varying(150) NOT NULL,
    gender character varying(20),
    last_notified_at timestamp(6) without time zone,
    last_notified_channel character varying(20),
    location character varying(200),
    motivation text,
    phone character varying(30),
    preferred_contact_channel character varying(20),
    reference_number character varying(30),
    reviewed_at timestamp(6) without time zone,
    reviewed_by bigint,
    status character varying(20) NOT NULL,
    talent_area character varying(30) NOT NULL,
    user_id bigint,
    CONSTRAINT talent_applications_applicant_category_check CHECK (((applicant_category)::text = ANY ((ARRAY['YOUTH'::character varying, 'SINGLE_MOTHER'::character varying, 'PERSON_WITH_DISABILITY'::character varying, 'ELDERLY'::character varying, 'PROFESSIONAL_ARTIST'::character varying, 'COMMUNITY_MEMBER'::character varying])::text[]))),
    CONSTRAINT talent_applications_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'AWAITING_INFO'::character varying, 'ARCHIVED'::character varying])::text[]))),
    CONSTRAINT talent_applications_talent_area_check CHECK (((talent_area)::text = ANY ((ARRAY['TRADITIONAL_DANCE'::character varying, 'STORYTELLING'::character varying, 'CULTURAL_PERFORMANCE'::character varying, 'MUSIC'::character varying, 'VISUAL_ARTS'::character varying, 'CRAFTS'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: talent_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.talent_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.talent_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: talent_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.talent_profiles (
    id bigint NOT NULL,
    category character varying(40) NOT NULL,
    created_at timestamp(6) without time zone,
    display_name character varying(150) NOT NULL,
    headline character varying(250),
    primary_image_url character varying(700),
    primary_media_id bigint,
    published boolean NOT NULL,
    story text,
    CONSTRAINT talent_profiles_category_check CHECK (((category)::text = ANY ((ARRAY['YOUTH'::character varying, 'SINGLE_MOTHER'::character varying, 'PERSON_WITH_DISABILITY'::character varying, 'ELDERLY'::character varying, 'PROFESSIONAL_ARTIST'::character varying, 'COMMUNITY_MEMBER'::character varying])::text[])))
);


--
-- Name: talent_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.talent_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.talent_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: testimonials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.testimonials (
    id bigint NOT NULL,
    author_country character varying(100),
    author_name character varying(150) NOT NULL,
    author_title character varying(150),
    created_at timestamp(6) without time zone,
    featured boolean NOT NULL,
    message text NOT NULL,
    published boolean NOT NULL,
    rating integer NOT NULL
);


--
-- Name: testimonials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.testimonials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.testimonials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tour_operator_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_operator_requests (
    id bigint NOT NULL,
    admin_notes text,
    company_name character varying(200) NOT NULL,
    contact_email character varying(150) NOT NULL,
    contact_name character varying(150) NOT NULL,
    contact_phone character varying(40),
    country character varying(100),
    created_at timestamp(6) without time zone,
    estimated_date date,
    estimated_group_size integer,
    invoice_required boolean NOT NULL,
    itinerary_asset_url character varying(700),
    last_notified_at timestamp(6) without time zone,
    last_notified_channel character varying(20),
    owner_email character varying(150),
    partner_price numeric(10,2),
    partner_price_currency character varying(3),
    preferred_contact_channel character varying(20),
    request_details text,
    request_type character varying(30),
    requested_experience_slug character varying(250),
    status character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT tour_operator_requests_request_type_check CHECK (((request_type)::text = ANY ((ARRAY['GROUP_BOOKING'::character varying, 'CUSTOM_PACKAGE'::character varying])::text[]))),
    CONSTRAINT tour_operator_requests_status_check CHECK (((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'UNDER_REVIEW'::character varying, 'INVOICE_PENDING'::character varying, 'CONFIRMED'::character varying, 'DECLINED'::character varying])::text[])))
);


--
-- Name: tour_operator_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tour_operator_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tour_operator_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    country character varying(100),
    created_at timestamp(6) without time zone,
    email character varying(100) NOT NULL,
    enabled boolean NOT NULL,
    first_name character varying(80) NOT NULL,
    last_name character varying(80) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(20),
    profile_image_url character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: webhook_event_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhook_event_logs (
    id bigint NOT NULL,
    error_message text,
    event_type character varying(100) NOT NULL,
    external_event_id character varying(100) NOT NULL,
    processed_at timestamp(6) without time zone,
    provider character varying(50) NOT NULL,
    status character varying(20) NOT NULL
);


--
-- Name: webhook_event_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.webhook_event_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.webhook_event_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_rate_limits api_rate_limits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_rate_limits
    ADD CONSTRAINT api_rate_limits_pkey PRIMARY KEY (id);


--
-- Name: audit_events audit_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);


--
-- Name: availability_slots availability_slots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.availability_slots
    ADD CONSTRAINT availability_slots_pkey PRIMARY KEY (id);


--
-- Name: blackout_dates blackout_dates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blackout_dates
    ADD CONSTRAINT blackout_dates_pkey PRIMARY KEY (id);


--
-- Name: blog_posts blog_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blog_posts
    ADD CONSTRAINT blog_posts_pkey PRIMARY KEY (id);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: consent_records consent_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consent_records
    ADD CONSTRAINT consent_records_pkey PRIMARY KEY (id);


--
-- Name: contact_inquiries contact_inquiries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_inquiries
    ADD CONSTRAINT contact_inquiries_pkey PRIMARY KEY (id);


--
-- Name: donation_campaigns donation_campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.donation_campaigns
    ADD CONSTRAINT donation_campaigns_pkey PRIMARY KEY (id);


--
-- Name: donations donations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.donations
    ADD CONSTRAINT donations_pkey PRIMARY KEY (id);


--
-- Name: experiences experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiences
    ADD CONSTRAINT experiences_pkey PRIMARY KEY (id);


--
-- Name: media_assets media_assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT media_assets_pkey PRIMARY KEY (id);


--
-- Name: notification_logs notification_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_logs
    ADD CONSTRAINT notification_logs_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: platform_settings platform_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_settings
    ADD CONSTRAINT platform_settings_pkey PRIMARY KEY (id);


--
-- Name: product_categories product_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);


--
-- Name: product_collections product_collections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_collections
    ADD CONSTRAINT product_collections_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: saved_items saved_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_items
    ADD CONSTRAINT saved_items_pkey PRIMARY KEY (id);


--
-- Name: shipping_orders shipping_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_orders
    ADD CONSTRAINT shipping_orders_pkey PRIMARY KEY (id);


--
-- Name: talent_applications talent_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.talent_applications
    ADD CONSTRAINT talent_applications_pkey PRIMARY KEY (id);


--
-- Name: talent_profiles talent_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.talent_profiles
    ADD CONSTRAINT talent_profiles_pkey PRIMARY KEY (id);


--
-- Name: testimonials testimonials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testimonials
    ADD CONSTRAINT testimonials_pkey PRIMARY KEY (id);


--
-- Name: tour_operator_requests tour_operator_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_operator_requests
    ADD CONSTRAINT tour_operator_requests_pkey PRIMARY KEY (id);


--
-- Name: carts uk2vfsg3befcsdo3hgq1jqi10yj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk2vfsg3befcsdo3hgq1jqi10yj UNIQUE (anon_session_id);


--
-- Name: experiences uk648dsce764vqs0mcv0s1iexk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiences
    ADD CONSTRAINT uk648dsce764vqs0mcv0s1iexk UNIQUE (slug);


--
-- Name: carts uk64t7ox312pqal3p7fg9o503c2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: product_categories uk6h198ar0xronfoxlvnq7lsfc0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT uk6h198ar0xronfoxlvnq7lsfc0 UNIQUE (slug);


--
-- Name: blackout_dates uk_blackout_experience_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blackout_dates
    ADD CONSTRAINT uk_blackout_experience_date UNIQUE (experience_id, date_value);


--
-- Name: availability_slots uk_experience_slot_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.availability_slots
    ADD CONSTRAINT uk_experience_slot_date UNIQUE (experience_id, slot_date);


--
-- Name: platform_settings uk_platform_setting_category_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_settings
    ADD CONSTRAINT uk_platform_setting_category_key UNIQUE (category, key_name);


--
-- Name: saved_items uk_saved_item_user_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_items
    ADD CONSTRAINT uk_saved_item_user_product UNIQUE (user_id, product_id);


--
-- Name: talent_applications ukd8larum3srkx87w2liiroblvb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.talent_applications
    ADD CONSTRAINT ukd8larum3srkx87w2liiroblvb UNIQUE (reference_number);


--
-- Name: bookings uke92mgyq35mdeo8gc1un2o6uk0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT uke92mgyq35mdeo8gc1un2o6uk0 UNIQUE (booking_reference);


--
-- Name: blog_posts ukfmrqlsu8hgt4xyp3ewt66h287; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blog_posts
    ADD CONSTRAINT ukfmrqlsu8hgt4xyp3ewt66h287 UNIQUE (slug);


--
-- Name: webhook_event_logs uki0vjcfnbusk5ucegdcvj8w1r3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_event_logs
    ADD CONSTRAINT uki0vjcfnbusk5ucegdcvj8w1r3 UNIQUE (external_event_id);


--
-- Name: product_collections uklu61781t92y0ktdt3i6uh2i19; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_collections
    ADD CONSTRAINT uklu61781t92y0ktdt3i6uh2i19 UNIQUE (slug);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: products ukostq1ec3toafnjok09y9l7dox; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukostq1ec3toafnjok09y9l7dox UNIQUE (slug);


--
-- Name: media_assets ukpyjesqee74frq8h67wtpf4f2t; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT ukpyjesqee74frq8h67wtpf4f2t UNIQUE (storage_key);


--
-- Name: shipping_orders ukrdgn5v7xqarjkxb0xa01fs7o9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_orders
    ADD CONSTRAINT ukrdgn5v7xqarjkxb0xa01fs7o9 UNIQUE (order_reference);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: webhook_event_logs webhook_event_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_event_logs
    ADD CONSTRAINT webhook_event_logs_pkey PRIMARY KEY (id);


--
-- Name: idx_audit_actor_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_actor_time ON public.audit_events USING btree (actor_user_id, created_at DESC);


--
-- Name: idx_audit_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_entity ON public.audit_events USING btree (entity_type, entity_id);


--
-- Name: blackout_dates fk1l22bl27n7865v0vm002nofo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blackout_dates
    ADD CONSTRAINT fk1l22bl27n7865v0vm002nofo FOREIGN KEY (experience_id) REFERENCES public.experiences(id);


--
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: saved_items fk3cr21muwck4nquy849ed917re; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_items
    ADD CONSTRAINT fk3cr21muwck4nquy849ed917re FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: shipping_orders fk64r5toa9o5gfse40t8mp69d1b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_orders
    ADD CONSTRAINT fk64r5toa9o5gfse40t8mp69d1b FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: products fk6t5dtw6tyo83ywljwohuc6g7k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk6t5dtw6tyo83ywljwohuc6g7k FOREIGN KEY (category_id) REFERENCES public.product_categories(id);


--
-- Name: bookings fk7o1ydixkywgg25tjguihg2tpo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk7o1ydixkywgg25tjguihg2tpo FOREIGN KEY (experience_id) REFERENCES public.experiences(id);


--
-- Name: blog_post_tags fk7tf83uatm3u6lm9mcthgr8vfh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blog_post_tags
    ADD CONSTRAINT fk7tf83uatm3u6lm9mcthgr8vfh FOREIGN KEY (post_id) REFERENCES public.blog_posts(id);


--
-- Name: donations fk8oswi2j67r6vj41jk31fx0evj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.donations
    ADD CONSTRAINT fk8oswi2j67r6vj41jk31fx0evj FOREIGN KEY (campaign_id) REFERENCES public.donation_campaigns(id);


--
-- Name: carts fkb5o626f86h46m4s7ms6ginnop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reviews fkcgy7qjc1r99dp117y9en6lxye; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: products fkctbegrqkrl48ne5ci5jyep2bp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkctbegrqkrl48ne5ci5jyep2bp FOREIGN KEY (collection_id) REFERENCES public.product_collections(id);


--
-- Name: donations fkd2p196clbvqgbemy05ndspwu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.donations
    ADD CONSTRAINT fkd2p196clbvqgbemy05ndspwu FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bookings fkeyog2oic85xg7hsu2je2lx3s6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fkeyog2oic85xg7hsu2je2lx3s6 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: saved_items fkfckoeh5tbj64qvkvv5ijc3hwi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_items
    ADD CONSTRAINT fkfckoeh5tbj64qvkvv5ijc3hwi FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: shipping_orders fkibaldeb67tashko6e17qop0to; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_orders
    ADD CONSTRAINT fkibaldeb67tashko6e17qop0to FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: talent_applications fkipb57yh1u3l41y3sc36b7te75; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.talent_applications
    ADD CONSTRAINT fkipb57yh1u3l41y3sc36b7te75 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: availability_slots fkitvkclsr9twl9x2nc1xrnyovx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.availability_slots
    ADD CONSTRAINT fkitvkclsr9twl9x2nc1xrnyovx FOREIGN KEY (experience_id) REFERENCES public.experiences(id);


--
-- Name: blog_posts fklog64k5g2l1679hjl2wuyyk5n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blog_posts
    ADD CONSTRAINT fklog64k5g2l1679hjl2wuyyk5n FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: reviews fkpl51cejpw4gy5swfar8br9ngi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkpl51cejpw4gy5swfar8br9ngi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: order_items fkpmwnwfu4u5qv2sfssa6kb3a35; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkpmwnwfu4u5qv2sfssa6kb3a35 FOREIGN KEY (order_id) REFERENCES public.shipping_orders(id);


--
-- Name: product_images fkqnq71xsohugpqwf3c9gxmsuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: experience_images fkqvbnucnylrs0uda3va4hsmcq6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experience_images
    ADD CONSTRAINT fkqvbnucnylrs0uda3va4hsmcq6 FOREIGN KEY (experience_id) REFERENCES public.experiences(id);


--
-- Name: reviews fkt6gj7yde2mbp38w5lpi5vmm9t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkt6gj7yde2mbp38w5lpi5vmm9t FOREIGN KEY (experience_id) REFERENCES public.experiences(id);


--
--


